events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name 72.56.245.141; # IP-адрес твоего сервера

        # Отдаем клиентскую часть (Frontend)
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Проксируем API-запросы к нашему FastAPI-серверу
        # В твоей курсовой указаны эндпоинты: /upload, /task, /download
        location ~ ^/(upload|task|download) {
            proxy_pass http://api_service:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Увеличиваем лимиты для загрузки больших документов
            client_max_body_size 50M; 
        }
    }
}